name: Deploy

on:
  push:
    branches:
      - action-dev
jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H brydonleonard.com >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          rsync -vrm  .output/* ${{ secrets.USER_ADDR }}:/usr/local/cloudflare_ddns/
          ssh ${{ secrets.USER_ADDR }} "pip install /usr/local/cloudflare_ddns/. && python3 /usr/local/cloudflare_ddns/cloudflare_ddns.py &"
