name: Deploy

on:
  push:
    branches:
      - action-dev-1
      - action-dev-2
      - action-dev-3
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Deploy and run DDNS
      uses: appleboy/ssh-action@master
      with:
        host: ssh.brydonleonard.com
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: 22
        command_timeout: 30m
        script: | 
          whoami
