name: Deploy

on:
  push:
    branches:
      - action-dev-1
      - action-dev-2
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Deploy and run DDNS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: brydonleonard.com
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        port: 22
        command_timeout: 30m
        script: | 
          rsync -vrm  .output/* ${{ secrets.USER_ADDR }}:/usr/local/cloudflare_ddns/
          ssh ${{ secrets.USER_ADDR }} "pip install /usr/local/cloudflare_ddns/. && python3 /usr/local/cloudflare_ddns/cloudflare_ddns.py &"
